### ISSUE TITLE
List at xmpp.org

### ISSUE THREAD

**Issue by Echolon** [paulfariello/aparte#23]
Ideally with a doap file :-) https://xmpp.org/extensions/inbox/doap-usage-in-xmpp.html

https://xmpp.org/software/clients/

**Comment by Echolon** [comment]
Kind reminder to this :)

**Comment by paulfariello** [comment]
Listed a few month ago, added doap in Aparte repository and opened a MR on xmpp.org https://github.com/xsf/xmpp.org/pull/1358

**Comment by cal0pteryx** [comment]
Hi @paulfariello 
It looks like an accent is missing in the DOAP file's name entry: https://github.com/paulfariello/aparte/blob/develop/doap.xml#L6

It says "Aparte" instead of "Aparté". I guess this should be changed to match the project's name? :)
I'd change it in the xmpp.org repo as well, if this is correct.

**Comment by paulfariello** [comment]
Thanks for reporting it. It has been fixed in bd6dac0aee79273b32b14bc6ad98a14fd42b2651.
